routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();
Route::get('/', 'Auth\LoginController@showLoginForm');
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('post', 'PostController');
Route::resource('category', 'CategoryController');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['title' ,'content', 'posts_slug','posts_image', 'category_id'];

    public function category() 
    {
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }
}

app/Http/Controllers/API/PostController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Post;

class PostController extends Controller
{

    /**
     * for request all data post and headline (with category)
     */
    public function index()
    {
        // Prepare data for Request Client 
        $headline = Post::orderBy('created_at', 'DESC')->first();
        $post = Post::whereNotIn('id', [$headline->id])->paginate(3);
        
        // make array all data 
        $headline = $headline->toArray();
        $posts = $post->toArray();

        // prepare response
        $res = [
            'success' => true,
            'headline' => $headline,
            'data' => $posts,
            'message' => 'Post Retrivied Successfully'
        ];

        // return response data
        return response()->json($res, 200);
    }

    /**
     *  for getting data specified slug
     */
    public function show($slug)
    {
        //  prepare data for Request Client
        $detail = Post::where('posts_slug', $slug)->with('category')->first();
        $post =  Post::whereNotIn('id', [$detail->id])->paginate(3);

        //  check if data not available 
        if (is_null($post)) {

            // prepare response if data not available
            $res = [
                'success' => false,
                'data' => 'Empty',
                'message' => 'Posts Not Found',
            ];

            // = return if not available 
            return response()->json($res, 200);
        }

        // make array if data available
        $posts = $post->toArray();
        $details = $detail->toArray();

        // prepare response
        $res = [
            'success' => true,
            'detail' => $details,
            'data' => $posts,
            'Message' => 'Post Retrievied Successfully',
        ];

        // return response data
        return response()->json($res, 200);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use App\Category;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use File;
use Alert;

class PostController extends Controller
{

    /**
     * 
     * check middleware
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * 
     * Menampilkan Halaman utama dari posts
     */
    public function index()
    {
        // menampilkan halaman utama posts dan kirim data 
        $post = Post::paginate(8);
        return view('dashboard.post.index', compact('post'));
    }

    /**
     * 
     * menampilkan halaman input post
     */
    public function create()
    {
        // menampilkan halaman input post dan kirim data 
        $category = Category::all();
        $post = Post::paginate(5);
        return view('dashboard.post.create', compact('category', 'post'));
    }

    /**
     * 
     * untuk memasukan data post
     */
    public function store(Request $request)
    {
        // cek validasi dari request form
        $request->validate([
            'title' => 'required',
            'content' => 'required',
            'posts_image' => 'image|dimensions:min_width=500, min_height=500',
            'category_id' => 'required',
        ]);

        // cek bila ada gambar yang di masukan
        if ($file = $request->file('posts_image')) {
            $filename = now() . $file->getClientOriginalName();
            $target_path = public_path('/img');
            $file->move($target_path, $filename);
        } else {
            $filename = asset('img/default.png');
        }

        // insert data post
        Post::create([
            'title' => $request->title,
            'content' => $request->content,
            'posts_slug' => Str::slug($request->title, '-'),
            'posts_image' => asset('img/' . $filename),
            'category_id' => $request->category_id
        ]);

        // kembali ke halaman sebelumnya dan tampilkan alert
        Alert::success('berhasil', 'Data Berhasil Di Tambahkan!');
        return redirect()->route('post.create');
    }

    /**
     *
     * menampilkan halaman edit post
     */
    public function edit(Post $post)
    {
        // menampilkan halaman edit post dan kirim data 
        $category = Category::all();
        return view('dashboard.post.edit', compact('post', 'category'));
    }

    /**
     * 
     * untuk update data post
     */
    public function update(Request $request, Post $post)
    {
        // cek validasi dari request form
        $request->validate([
            'title' => 'required',
            'content' => 'required',
            'posts_image' => 'image|dimensions:min_width=500, min_height=500',
            'category_id' => 'required',
        ]);

        // cek jika ada gambar yang di update
        if ($file = $request->file('posts_image')) {
            if ($post->posts_image !== 'default.png') {
                File::delete('img/' . $post->posts_image);
            }
            $filename = asset('img/' . now() . $file->getClientOriginalName());
            $target_path = public_path('/img');
            $file->move($target_path, $filename);
        } else {
            $filename =  $post->posts_image;
        }

        // update data post
        Post::where('id', $post->id)
            ->update([
                'title' => $request->title,
                'content' => $request->content,
                'posts_slug' => Str::slug($request->title, '-'),
                'posts_image' => $filename,
                'category_id' => $request->category_id
            ]);

        // kembali ke halaman sebelumnya dan tampilkan alert
        Alert::success('berhasil', 'Data Berhasil Di Ubah!');
        return redirect()->route('post.index');
    }

    /**
     * 
     * untuk delete data post
     */
    public function destroy(Post $post)
    {
        // hapus data kategori berdasarkan data yang di kirim di form 
        Post::destroy($post->id);
        // hapus gambar jika bukan default.png 
        if ($post->posts_image !== 'default.png') {
            File::delete('img/' . $post->posts_image);
        }
        // kembali ke halaman sebelumnya dan tampilkan alert
        Alert::success('berhasil', 'Data Berhasil Di Hapus!');
        return redirect()->route('post.index');
    }
}

resources/views/dashboard/post/create.blade.php
@extends('layouts.main')

@section('title', 'Posts')


@section('content')
<main class="main-content">
    <div class="breadcrumb d-flex align-items-center pd-20 pb-0">

        <div>
            <a href="{{ route('home') }}">
                <i class="icon-home"></i> Home
            </a>
        </div>

        <div class="breadcrumb-sep">
            <i class="icon-chevron-right"></i>
        </div>

        <div>
            <a href="{{ route('post.index') }}">Post</a>
        </div>

        <div class="breadcrumb-sep">
            <i class="icon-chevron-right"></i>
        </div>

        <div>Add New Post</div>

    </div>

    <!-- content -->
    <div class="pd-20 pt-0">
        <!-- Main Card -->
        <div class="card mt-3">
            <!-- Card Body  -->
            <div class="card-body">
                <h6 class="card-title mb-4">Add New Post</h6>
                <hr style="border: 1px solid #1B1D4E;">


                <form action="{{ route('post.store') }}" method="POST" enctype="multipart/form-data">@csrf
                    <!-- If Form Errors -->
                    @if($errors->any())
                    <div class="row">
                        <div class="col-12">
                            <div class="alert alert-danger fade show" role="alert">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                    </div>
                    @endif
                    <!-- If Form Errors -->

                    <!-- row -->
                    <div class="row">
                        <!-- col -->
                        <div class="col-12 col-lg-8">
                            <div class="card shadow-md">
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="title">Title</label>
                                        <input type="text" class="form-control" id="title"
                                            placeholder="Insert title post" name="title" value="{{ @old('title') }}">
                                    </div>
                                    <div class="form-group">
                                        <textarea class="form-control" id="summernote" rows="20" name="content">
                                            {{ @old('content') }}
                                        </textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- end of col -->

                        <!-- col -->
                        <div class="col-12 col-lg-4 mt-3 mt-lg-0">
                            <!-- card -->
                            <div class="card shadow-md">
                                <!-- card body -->
                                <div class="card-body">
                                    @foreach ($category as $categories)
                                    <div class="form-check my-2">
                                        <input class="form-check-input" type="radio" name="category_id"
                                            value="{{ $categories->id }}">
                                        <label class="form-check-label" for="exampleRadios1">
                                            {{ $categories->title }}
                                        </label>
                                    </div>
                                    @endforeach

                                </div>
                                <!-- end of card body -->
                            </div>
                            <!-- end of card -->

                            <!-- card -->
                            <div class="card mt-3">
                                <!-- card body -->
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="posts_image">Image</label>
                                        <input type="file" class="form-control-file" id="posts_image" name="posts_image"
                                            onchange="readURL(this)">
                                    </div>
                                    <img src="#" alt="" id="img" class="img-fluid">
                                </div>
                                <!-- end of card body -->
                            </div>
                            <!-- end of card -->

                            <button type="submit" class="btn btn-dark btn-round-left w-100 my-3">Publish</button>
                        </div>
                        <!-- end of col -->
                    </div>
                    <!-- end of row -->
                </form>
            </div>
            <!-- End Of Card Body -->
        </div>
        <!-- end of Main Card -->
    </div>
    <!-- End Of Content -->
</main>
@endsection

@section('js')
<script>
    $(function() {
        // hilangkan alert jika ada error
        setTimeout(function() {
            $('.alert').alert('close');
        },5000)

        // ckeditor
       $('#summernote').summernote({
            height: 250,
            maximumImageFileSize: 2097152,
            toolbar: [
                ['style', ['bold', 'italic', 'underline']],
                ['fontsize', ['fontsize']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['insert', ['picture', 'link']], 
                ["view", ["fullscreen", "codeview"]]
            ]
        });
    });

    // untuk preview image sebelum upload
    function readURL(input) {
        var url = input.value;
        var ext = url.substring(url.lastIndexOf('.') + 1).toLowerCase();
        if (input.files && input.files[0]&& (ext == "gif" || ext == "png" || ext == "jpeg" || ext == "jpg")) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#img').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        } else{
            $('#img').attr('src', '/assets/no_preview.png');
        }
    }
</script>
@endsection

resources/views/dashboard/post/edit.blade.php
@extends('layouts.main')

@section('title', 'Posts')


@section('content')
<main class="main-content">
    <div class="breadcrumb d-flex align-items-center pd-20 pb-0">

        <div>
            <a href="{{ route('home') }}">
                <i class="icon-home"></i> Home
            </a>
        </div>

        <div class="breadcrumb-sep">
            <i class="icon-chevron-right"></i>
        </div>

        <div>
            <a href="{{ route('post.index') }}">Post</a>
        </div>

        <div class="breadcrumb-sep">
            <i class="icon-chevron-right"></i>
        </div>

        <div>Edit Data Post</div>

    </div>

    <!-- content -->
    <div class="pd-20 pt-0">
        <!-- Main Card -->
        <div class="card mt-3">
            <!-- Card Body  -->
            <div class="card-body">
                <h6 class="card-title mb-4">Edit Data Post</h6>
                <hr style="border: 1px solid #1B1D4E;">


                <form action="{{ url('post') . '/' . $post->id }} " method="POST" enctype="multipart/form-data">
                    @csrf @method('put')
                    <!-- If Form Errors -->
                    @if($errors->any())
                    <div class="row">
                        <div class="col-12">
                            <div class="alert alert-danger fade show" role="alert">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                    </div>
                    @endif
                    <!-- If Form Errors -->

                    <!-- row -->
                    <div class="row">
                        <!-- col -->
                        <div class="col-12 col-lg-8">
                            <div class="card shadow-md">
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="title">Title</label>
                                        <input type="text" class="form-control" id="title"
                                            placeholder="Insert title post" name="title" value="{{ $post->title }}">
                                    </div>

                                    <div class="form-group">
                                        <textarea class="form-control" id="summernote" rows="20" name="content">
                                                {{ $post->content }}
                                        </textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- end of col -->

                        <!-- col -->
                        <div class="col-12 col-lg-4 mt-3 mt-lg-0">
                            <!-- card -->
                            <div class="card">
                                <!-- card body -->
                                <div class="card-body">
                                    @foreach ($category as $categories)
                                    <div class="form-check my-2">
                                        @if($categories->id == $post->category_id)
                                        <input class="form-check-input" type="radio" name="category_id"
                                            value="{{ $categories->id }}" checked>
                                        @else
                                        <input class="form-check-input" type="radio" name="category_id"
                                            value="{{ $categories->id }}">
                                        @endif
                                        <label class="form-check-label" for="exampleRadios1">
                                            {{ $categories->title }}
                                        </label>
                                    </div>
                                    @endforeach
                                </div>
                                <!-- end of card body -->
                            </div>
                            <!-- end of card -->

                            <!-- card -->
                            <div class="card mt-4">
                                <!-- card body -->
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="posts_image">Image</label>
                                        <input type="file" class="form-control-file" id="posts_image" name="posts_image"
                                            onchange="readURL(this)" value="{{ $post->posts_image }}">
                                    </div>
                                    <img src="{{ $post->posts_image }}" alt="" id="img" class="img-fluid">
                                </div>
                                <!-- end of card body -->
                            </div>
                            <!-- end of card -->

                            <button type="submit" class="btn btn-dark btn-round-left w-100 my-3">
                                Update Content
                            </button>
                        </div>
                        <!-- end of col -->
                    </div>
                    <!-- end of row -->
                </form>
            </div>
            <!-- End Of Card Body -->
        </div>
        <!-- end of Main Card -->
    </div>
    <!-- End Of Content -->
</main>
@endsection

@section('js')
<script>
    $(function() {
        setTimeout(function() {
        $('.alert').alert('close')
        },5000)

        $('#summernote').summernote({
            height: 250,
            maximumImageFileSize: 2097152,
            toolbar: [
                ['style', ['bold', 'italic', 'underline']],
                ['fontsize', ['fontsize']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['insert', ['picture', 'link']], 
                ["view", ["fullscreen", "codeview"]]
            ]
        });
    });
        function readURL(input) {
            var url = input.value;
            var ext = url.substring(url.lastIndexOf('.') + 1).toLowerCase();
        if (input.files && input.files[0]&& (ext == "gif" || ext == "png" || ext == "jpeg" || ext == "jpg")) {
            var reader = new FileReader();
            reader.onload = function (e) {
            $('#img').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>
@endsection

resources/views/dashboard/post/index.blade.php
@extends('layouts.main')

@section('title', 'Posts')


@section('content')
<main class="main-content">
    <div class="breadcrumb d-flex align-items-center pd-20 pb-0">
        <div>
            <a href="{{ route('home') }}">
                <i class="icon-home"></i> Home
            </a>
        </div>

        <div class="breadcrumb-sep">
            <i class="icon-chevron-right"></i>
        </div>

        <div>
            Post
        </div>

    </div>
    <div class="pd-20 pt-0">
        <!-- card -->
        <div class="card mt-3">
            <!-- card body -->
            <div class="card-body">
                <h6 class="card-title mb-4">Post</h6>
                <hr style="border: 1px solid #1B1D4E;">

                <div class="row overflow-auto">
                    <div class="col-lg">
                        <table class="table table-hover text-center">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">image</th>
                                    <th scope="col">Title</th>
                                    <th scope="col">Category</th>
                                    <th scope="col">Created At</th>
                                    <th scope="col" colspan="2">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($post as $posts)
                                <tr>
                                    <th scope="row">{{ $loop->iteration }}</th>
                                    <th><img src="{{ $posts->posts_image }}" width="60px" alt="">
                                    </th>
                                    <td>{{ $posts->title }}</td>
                                    <td>{{ $posts->category->title }}</td>
                                    <td>{{ $posts->created_at->format('d M yy') }}</td>
                                    <td>
                                        <a href="{{ url('post') . '/' .  $posts->id . '/edit' }}"
                                            class="btn btn-primary btn-sm">Edit</a>
                                    </td>
                                    <td>
                                        <form action="{{ route('post.destroy',  $posts->id)  }}"
                                            id="formDelete-post{{ $posts->id }}" method="post">
                                            @method('delete')
                                            @csrf
                                            <button type="button" class="btn btn-danger btn-sm"
                                                onclick="deleteData({{ $posts->id }})">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>


            </div>
            <!-- end of card body -->
        </div>
        <!-- end of card -->
    </div>
</main>
@endsection

@section('js')
<script>
    function deleteData(id) {
            Swal.fire({
                title: 'Apakah Anda Yakin?',
                text: "Data yang dihapus tidak dapat dikembalikan!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ya, Hapus!',
                cancelButtonText: 'Kembali'
            }).then((result) => {
                if (result.value) {
                    $('#formDelete-post' + id).submit();
                }
            })
        }
</script>
@endsection