routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();
Route::get('/', 'Auth\LoginController@showLoginForm');
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('post', 'PostController');
Route::resource('category', 'CategoryController');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['title', 'cat_slug'];

    public function post() 
    {
        return $this->hasMany('App\Category');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Alert;


class CategoryController extends Controller
{
    /**
     * check middleware
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * 
     * Menampilkan Halaman Utama Category
     */
    public function index()
    {
        // menampilkan halaman kategori dan kirim semua data kategori
        $category = Category::paginate(5);
        return view('dashboard.category.index', compact('category'));
    }

    /**
     * 
     * Untuk Memasukan data Categori
     */
    public function store(Request $request)
    {
        // cek validasi dari request form
        $request->validate([
            'title' => 'required'
        ]);

        // insert data kategori
        Category::create([
            'title' => $request->title,
            'cat_slug' => Str::slug($request->title, '-')
        ]);

        // kembali ke halaman sebelumnya dan tampilkan alert
        Alert::success('Berhasil!', 'Data Berhasil Di Tambahkan!');
        return back();
    }

    /**
     * 
     * Untuk Update Data Category
     */
    public function update(Request $request, Category $category)
    {
        // cek validasi dari request form
        $request->validate([
            'title' => 'required'
        ]);

        // update data kategori
        Category::where('id', $category->id)
            ->update([
                'title' => $request->title,
                'cat_slug' => Str::slug($request->title, '-')
            ]);

        // kembali ke halaman sebelumnya dan tampilkan alert
        Alert::success('Berhasil!', 'Data Berhasil Di Update!');
        return back();
    }

    /**
     * 
     *  untuk delete data category
     * ! Check bila data tidak bisa di hapus 
     */
    public function destroy(Category $category)
    {
        // hapus data kategori berdasarkan data yang di kirim di form 
        Category::destroy($category->id);

        // kembali ke halaman sebelumnya dan tampilkan alert
        Alert::success('Berhasil!', 'Data Berhasil Di Delete!');
        return back();
    }
}

resources/views/dashboard/category/index.blade.php
@extends('layouts.main')

@section('title', 'Category')



@section('content')
<main class="main-content">
    <div class="breadcrumb d-flex align-items-center pd-20 pb-0">
        <div>
            <a href="{{ route('home') }}">
                <i class="icon-home"></i> Home
            </a>
        </div>

        <div class="breadcrumb-sep">
            <i class="icon-chevron-right"></i>
        </div>

        <div>Category</div>
    </div>

    <!-- Main content -->
    <div class="pd-20 pt-0">
        <!-- card -->
        <div class="card mt-3">
            <!-- card body -->
            <div class="card-body">
                <h6 class="card-title mb-4">Category</h6>
                <hr style="border: 1px solid #1B1D4E;">

                <!-- row -->
                <div class="row">
                    <!-- col -->
                    <div class="col-12 col-lg-8">

                        @error('title')
                        <div class="alert alert-danger" role="alert">
                            {{ $message }}
                        </div>
                        @enderror

                        <form action="{{ route('category.store') }}" method="post" class="mb-4">
                            @csrf
                            <div class="input-group">
                                <input type="text" class="form-control" name="title" required
                                    placeholder="Category Name">
                                <div class="input-group-append">
                                    <button class="btn btn-dark btn-round border-0" type="submit">Add</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- end of col -->
                </div>
                <!-- end of row -->

                <!-- row -->
                <div class="row">
                    <!-- col -->
                    <div class="col-12  col-lg-8 overflow-auto">
                        <table class="table table-bordered table-hover text-center">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Category Name</th>
                                    <th scope="col">Created At</th>
                                    <th scope="col" colspan="2">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($category as $categories)
                                <tr>
                                    <th scope="row">{{ $loop->iteration }}</th>
                                    <td>{{ $categories->title }}</td>
                                    <td>{{ $categories->created_at->format('d M yy') }}</td>
                                    <td>
                                        <button class="btn btn-primary btn-sm" id="btnUpdate-category"
                                            data-title="{{ $categories->title }}"
                                            data-id='{{ $categories->id }}'>Update</button>
                                    </td>
                                    <td>
                                        <form action="{{ url('/category') . '/' . $categories->id }}"
                                            id="formDelete-category{{ $categories->id }}" method="post">
                                            @method('delete')
                                            @csrf
                                            <button type="button" class="btn btn-danger btn-sm"
                                                onclick="deleteData({{ $categories->id }})">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>

                        <div class="float-right">
                            {{ $category->links() }}
                        </div>
                    </div>
                    <!-- end of col -->
                </div>
                <!-- end of row -->
            </div>
            <!-- end card body -->
        </div>
        <!-- end of card -->
    </div>
    <!-- end of main content -->
</main>

<form id="formUpdate-category" method="post" class="mb-4">
    <div class="modal fade" id="modalUpdate-category" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog  modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Update Data Category</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @method('put')
                    @csrf
                    <input type="hidden" name="id" id="update-id">
                    <div class="input-group ">
                        <input type="text" class="form-control" name="title" id="update-title" required
                            placeholder="Category Name">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-dark">Edit</button>
                </div>
            </div>
        </div>
    </div>
</form>
@endsection
@section('js')
<script>
    $(function( ) {
        $(document).on('click','#btnUpdate-category', function() {
            $('#update-id').val($(this).attr('data-id'));
            $('#update-title').val($(this).attr('data-title'));
            $('#formUpdate-category').attr('action','/category/' + $(this).attr('data-id'));
            $('#modalUpdate-category').modal('show');
        }); 
    });

    function deleteData(id) {
        Swal.fire({
            title: 'Apakah Anda Yakin?',
            text: "Data yang dihapus tidak dapat dikembalikan!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Ya, Hapus!',
            cancelButtonText: 'Kembali'
        }).then((result) => {
            if (result.value) {
                $('#formDelete-category' + id).submit();
            }
        })
    }
</script>
@endsection